//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8784
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameStop.Common.Services.Security
{
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseResource", Namespace="http://schemas.datacontract.org/2004/07/GameStop.Common.Services.Security")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GameStop.Common.Services.Security.SQLResource))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GameStop.Common.Services.Security.APIResource))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GameStop.Common.Services.Security.ServiceResource))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GameStop.Common.Services.Security.QueueResource))]
    public partial class BaseResource : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string UserIDField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                this.UserIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SQLResource", Namespace="http://schemas.datacontract.org/2004/07/GameStop.Common.Services.Security")]
    public partial class SQLResource : GameStop.Common.Services.Security.BaseResource
    {
        
        private string DatabaseNameField;
        
        private string ServerNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DatabaseName
        {
            get
            {
                return this.DatabaseNameField;
            }
            set
            {
                this.DatabaseNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServerName
        {
            get
            {
                return this.ServerNameField;
            }
            set
            {
                this.ServerNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="APIResource", Namespace="http://schemas.datacontract.org/2004/07/GameStop.Common.Services.Security")]
    public partial class APIResource : GameStop.Common.Services.Security.BaseResource
    {
        
        private string DatabaseNameField;
        
        private string ServerNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DatabaseName
        {
            get
            {
                return this.DatabaseNameField;
            }
            set
            {
                this.DatabaseNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServerName
        {
            get
            {
                return this.ServerNameField;
            }
            set
            {
                this.ServerNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceResource", Namespace="http://schemas.datacontract.org/2004/07/GameStop.Common.Services.Security")]
    public partial class ServiceResource : GameStop.Common.Services.Security.BaseResource
    {
        
        private System.Uri ServiceUriField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Uri ServiceUri
        {
            get
            {
                return this.ServiceUriField;
            }
            set
            {
                this.ServiceUriField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueueResource", Namespace="http://schemas.datacontract.org/2004/07/GameStop.Common.Services.Security")]
    public partial class QueueResource : GameStop.Common.Services.Security.BaseResource
    {
        
        private string QueueNameField;
        
        private System.Uri ResourceUriField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QueueName
        {
            get
            {
                return this.QueueNameField;
            }
            set
            {
                this.QueueNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Uri ResourceUri
        {
            get
            {
                return this.ResourceUriField;
            }
            set
            {
                this.ResourceUriField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CredentialResponse", Namespace="http://schemas.datacontract.org/2004/07/GameStop.Common.Services.Security")]
    public partial class CredentialResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string PasswordField;
        
        private string UserIDField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                this.UserIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExpectedFault", Namespace="http://schemas.datacontract.org/2004/07/GameStop.Common.Services.Security")]
    public partial class ExpectedFault : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string MessageField;
        
        private string ReasonField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason
        {
            get
            {
                return this.ReasonField;
            }
            set
            {
                this.ReasonField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SenderFault", Namespace="http://schemas.datacontract.org/2004/07/GameStop.Common.Services.Security")]
    public partial class SenderFault : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ErrorsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Errors
        {
            get
            {
                return this.ErrorsField;
            }
            set
            {
                this.ErrorsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReceiverFault", Namespace="http://schemas.datacontract.org/2004/07/GameStop.Common.Services.Security")]
    public partial class ReceiverFault : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CodeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://www.gamestop.com/SecurityService/V1.0/ISecurityService", ConfigurationName="ISecurityService")]
public interface ISecurityService
{
    
    // CODEGEN: Generating message contract since the wrapper name (GetCredentialRequest) of message GetCredentialRequest does not match the default value (GetCredentials)
    [System.ServiceModel.OperationContractAttribute(Action="http://www.gamestop.com/SecurityService/V1.0/ISecurityService/ISecurityService/Ge" +
        "tCredentials", ReplyAction="http://www.gamestop.com/SecurityService/V1.0/ISecurityService/ISecurityService/Ge" +
        "tCredentialsResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(GameStop.Common.Services.Security.ExpectedFault), Action="http://www.gamestop.com/SecurityService/V1.0/ISecurityService/ISecurityService/Ge" +
        "tCredentialsExpectedFaultFault", Name="ExpectedFault", Namespace="http://schemas.datacontract.org/2004/07/GameStop.Common.Services.Security")]
    [System.ServiceModel.FaultContractAttribute(typeof(GameStop.Common.Services.Security.SenderFault), Action="http://www.gamestop.com/SecurityService/V1.0/ISecurityService/ISecurityService/Ge" +
        "tCredentialsSenderFaultFault", Name="SenderFault", Namespace="http://schemas.datacontract.org/2004/07/GameStop.Common.Services.Security")]
    [System.ServiceModel.FaultContractAttribute(typeof(GameStop.Common.Services.Security.ReceiverFault), Action="http://www.gamestop.com/SecurityService/V1.0/ISecurityService/ISecurityService/Ge" +
        "tCredentialsReceiverFaultFault", Name="ReceiverFault", Namespace="http://schemas.datacontract.org/2004/07/GameStop.Common.Services.Security")]
    GetCredentialResponse GetCredentials(GetCredentialRequest request);
    
    // CODEGEN: Generating message contract since the wrapper name (GetServiceAliveRequest) of message GetServiceAliveRequest does not match the default value (GetServiceAlive)
    [System.ServiceModel.OperationContractAttribute(Action="http://www.gamestop.com/SecurityService/V1.0/ISecurityService/ISecurityService/Ge" +
        "tServiceAlive", ReplyAction="http://www.gamestop.com/SecurityService/V1.0/ISecurityService/ISecurityService/Ge" +
        "tServiceAliveResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(GameStop.Common.Services.Security.ReceiverFault), Action="http://www.gamestop.com/SecurityService/V1.0/ISecurityService/ISecurityService/Ge" +
        "tServiceAliveReceiverFaultFault", Name="ReceiverFault", Namespace="http://schemas.datacontract.org/2004/07/GameStop.Common.Services.Security")]
    GetServiceAliveResponse GetServiceAlive(GetServiceAliveRequest request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetCredentialRequest", WrapperNamespace="http://www.gamestop.com/SecurityService/V1.0/ISecurityService", IsWrapped=true)]
public partial class GetCredentialRequest
{
    
    [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.gamestop.com/SecurityService/V1.0/ISecurityService")]
    public string ApplicationName;
    
    [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.gamestop.com/SecurityService/V1.0/ISecurityService")]
    public string HostName;
    
    [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.gamestop.com/SecurityService/V1.0/ISecurityService")]
    public string IPAddress;
    
    [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.gamestop.com/SecurityService/V1.0/ISecurityService")]
    public string UserId;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gamestop.com/SecurityService/V1.0/ISecurityService", Order=0)]
    public GameStop.Common.Services.Security.BaseResource Resource;
    
    public GetCredentialRequest()
    {
    }
    
    public GetCredentialRequest(string ApplicationName, string HostName, string IPAddress, string UserId, GameStop.Common.Services.Security.BaseResource Resource)
    {
        this.ApplicationName = ApplicationName;
        this.HostName = HostName;
        this.IPAddress = IPAddress;
        this.UserId = UserId;
        this.Resource = Resource;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetCredentialResponse", WrapperNamespace="http://www.gamestop.com/SecurityService/V1.0/ISecurityService", IsWrapped=true)]
public partial class GetCredentialResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gamestop.com/SecurityService/V1.0/ISecurityService", Order=0)]
    public string AuthenticationType;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gamestop.com/SecurityService/V1.0/ISecurityService", Order=1)]
    public GameStop.Common.Services.Security.CredentialResponse Credential;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gamestop.com/SecurityService/V1.0/ISecurityService", Order=2)]
    public int ErrorCode;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gamestop.com/SecurityService/V1.0/ISecurityService", Order=3)]
    public string ErrorMessage;
    
    public GetCredentialResponse()
    {
    }
    
    public GetCredentialResponse(string AuthenticationType, GameStop.Common.Services.Security.CredentialResponse Credential, int ErrorCode, string ErrorMessage)
    {
        this.AuthenticationType = AuthenticationType;
        this.Credential = Credential;
        this.ErrorCode = ErrorCode;
        this.ErrorMessage = ErrorMessage;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetServiceAliveRequest", WrapperNamespace="http://www.gamestop.com/SecurityService/V1.0/ISecurityService", IsWrapped=true)]
public partial class GetServiceAliveRequest
{
    
    public GetServiceAliveRequest()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetServiceAliveResponse", WrapperNamespace="http://www.gamestop.com/SecurityService/V1.0/ISecurityService", IsWrapped=true)]
public partial class GetServiceAliveResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gamestop.com/SecurityService/V1.0/ISecurityService", Order=0)]
    public System.DateTime SystemDateTime;
    
    public GetServiceAliveResponse()
    {
    }
    
    public GetServiceAliveResponse(System.DateTime SystemDateTime)
    {
        this.SystemDateTime = SystemDateTime;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface ISecurityServiceChannel : ISecurityService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class SecurityServiceClient : System.ServiceModel.ClientBase<ISecurityService>, ISecurityService
{
    
    public SecurityServiceClient()
    {
    }
    
    public SecurityServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public SecurityServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public SecurityServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public SecurityServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetCredentialResponse ISecurityService.GetCredentials(GetCredentialRequest request)
    {
        return base.Channel.GetCredentials(request);
    }
    
    public string GetCredentials(string ApplicationName, string HostName, string IPAddress, string UserId, GameStop.Common.Services.Security.BaseResource Resource, out GameStop.Common.Services.Security.CredentialResponse Credential, out int ErrorCode, out string ErrorMessage)
    {
        GetCredentialRequest inValue = new GetCredentialRequest();
        inValue.ApplicationName = ApplicationName;
        inValue.HostName = HostName;
        inValue.IPAddress = IPAddress;
        inValue.UserId = UserId;
        inValue.Resource = Resource;
        GetCredentialResponse retVal = ((ISecurityService)(this)).GetCredentials(inValue);
        Credential = retVal.Credential;
        ErrorCode = retVal.ErrorCode;
        ErrorMessage = retVal.ErrorMessage;
        return retVal.AuthenticationType;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetServiceAliveResponse ISecurityService.GetServiceAlive(GetServiceAliveRequest request)
    {
        return base.Channel.GetServiceAlive(request);
    }
    
    public System.DateTime GetServiceAlive()
    {
        GetServiceAliveRequest inValue = new GetServiceAliveRequest();
        GetServiceAliveResponse retVal = ((ISecurityService)(this)).GetServiceAlive(inValue);
        return retVal.SystemDateTime;
    }
}
